// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9b-FbkeqFjKqj86EXbfjfHk8xRH8MG0M',
    appId: '1:15738567745:android:c05cbdb6bfb276b787dac0',
    messagingSenderId: '15738567745',
    projectId: 'weeu-36e39',
    storageBucket: 'weeu-36e39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxz1AYyRNNrUfW5dyXNgSgXLLnKSjrXK0',
    appId: '1:15738567745:ios:2dd51b2ed6e77de487dac0',
    messagingSenderId: '15738567745',
    projectId: 'weeu-36e39',
    storageBucket: 'weeu-36e39.appspot.com',
    iosClientId: '15738567745-9q42k34h1464tsrf64jbfg7t273v8pss.apps.googleusercontent.com',
    iosBundleId: 'com.example.weu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxz1AYyRNNrUfW5dyXNgSgXLLnKSjrXK0',
    appId: '1:15738567745:ios:b021256a98db90a487dac0',
    messagingSenderId: '15738567745',
    projectId: 'weeu-36e39',
    storageBucket: 'weeu-36e39.appspot.com',
    iosClientId: '15738567745-p1jdcqhvn94jacub4ds0skv1if31en16.apps.googleusercontent.com',
    iosBundleId: 'com.weu',
  );
}
