// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9b-FbkeqFjKqj86EXbfjfHk8xRH8MG0M',
    appId: '1:15738567745:android:e8bde7e006d96cf687dac0',
    messagingSenderId: '15738567745',
    projectId: 'weeu-36e39',
    storageBucket: 'weeu-36e39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxz1AYyRNNrUfW5dyXNgSgXLLnKSjrXK0',
    appId: '1:15738567745:ios:58824471f067625287dac0',
    messagingSenderId: '15738567745',
    projectId: 'weeu-36e39',
    storageBucket: 'weeu-36e39.appspot.com',
    androidClientId: '15738567745-q8ed68oqhm2tica0ri52t5nt7sac572b.apps.googleusercontent.com',
    iosClientId: '15738567745-jnkfhhm06nla5da2vaf4kagpupghs3ib.apps.googleusercontent.com',
    iosBundleId: 'com.weeu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxz1AYyRNNrUfW5dyXNgSgXLLnKSjrXK0',
    appId: '1:15738567745:ios:a247f385a0cd810587dac0',
    messagingSenderId: '15738567745',
    projectId: 'weeu-36e39',
    storageBucket: 'weeu-36e39.appspot.com',
    androidClientId: '15738567745-q8ed68oqhm2tica0ri52t5nt7sac572b.apps.googleusercontent.com',
    iosBundleId: '-',
  );
}
