# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'


pod 'FirebaseAnalytics'
pod 'FirebaseAuth'
pod 'FirebaseFirestore'
pod 'Firebase', :modular_headers => true
pod 'FirebaseCore', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true
 $RNFirebaseAsStaticFramework = true

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  use_modular_headers!

  # Pods for Runner
  
  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
